### ISSUE TITLE
Additional description needed for databases.databases

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/postgres-release#14]
Hello maintainers of `postgres-release`,

Today we were looking over our BOSH manifest, and noticed that we'd defined some database config that looked like:
```
databases:
- tag: uaa
  name: uaa
```

We were wondering what the `tag` was for and whether it was still used. When we looked at your [job spec file](https://github.com/cloudfoundry/postgres-release/blob/master/jobs/postgres/spec#L28), there wasn't any explanation for the expected contents of each hash in the list. We started to dig through your job templates, but didn't find a mention of the `tag` key. As a general convention in BOSH releases, it would be great to always provide an example or extended description for lists of hashes, to enumerate the available keys and their uses. We're also curious about the exact purpose of `tag` in this context, and whether we can remove it from our manifest.

Thanks!
Dave and Raina (@rainmaker)
PCF Release Engineering

**Comment by valeriap** [comment]
@davewalter @rainmaker 
I confirm that `databases.databases[n].tag` is not used.
You can find a description of the properties in the [README](https://github.com/cloudfoundry/postgres-release#customizing).
We will make it more clear by adding some example to the spec and by removing the tag property from the sample templates.
Thanks.

**Comment by davewalter** [comment]
Thanks for the clarification.
