### ISSUE TITLE
Startup scripts silently fail if DB password include a '$'

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/postgres-release#21]
If you include a password containing a '$' under `databases.roles`, the postgres job will report as running but the DB won't have a password set. In `/var/vcap/sys/log/postgres/postgres_ctl.err.log` I see: 

```
[2017-08-18 20:46:02+0000] + echo 'Setting password for role cloud_controller...'
[2017-08-18 20:46:02+0000] /var/vcap/jobs/postgres/bin/postgres_start.sh: line 81: $6: unbound variable
```

My cloud_controller DB password does have a '...$6...' in the middle. Looks like [this line](https://github.com/cloudfoundry/postgres-release/blob/1b76e67afe480da60e07378c2b8414d7ff8c3738/jobs/postgres/templates/utils.sh.erb#L35) is not doing any escaping so special characters get expanded. On CAPI we usually use Ruby's `Shellwords.shellescape` in our ERB templates around passwords.

Also a big +1 on this comment around failing the job if setting the roles fails: https://github.com/cloudfoundry/postgres-release/blob/865224b83361d58e8a5bbef77ccee48429feae45/jobs/postgres/templates/postgres_ctl.erb#L31-L37. Would have been much easier to debug if the postgres job failing immediately rather than silently erroring.

**Comment by valeriap** [comment]
@ljfranklin 
Thanks for reporting this issue. We have opened a separate [story](https://www.pivotaltracker.com/story/show/150403719) to have the postgres job to fail when a query fails.
For the empty password issue, we have fixed it as suggested and you will find the fix in the next release.

**Comment by valeriap** [comment]
The empty password issue has been fixed in [v21](https://github.com/cloudfoundry/postgres-release/releases/tag/v21).
