### ISSUE TITLE
DB password including '!' is set incorrectly.

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/postgres-release#29]
'!' chars in the DB password are quoted incorrectly in utils.sh that creates users and DBs.

This regression was introduced most likely by https://github.com/cloudfoundry/postgres-release/commit/53dd31e4fe878955ffaf076cdcae6b55100adcd7

**Comment by valeriap** [comment]
@stephanme 
Thanks for reporting this issue.
The fix in included in [v24](https://github.com/cloudfoundry/postgres-release/releases/tag/v24).
