### ISSUE TITLE
Bump to 9.6.6 for CVEs

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry/postgres-release#35]
https://www.postgresql.org/support/security/ shows a few CVEs from November 2017 fixed in 9.6.6 that we'd like to see rolled out in this release.

**Comment by valeriap** [comment]
@svrc-pivotal 
[Release v25](https://github.com/cloudfoundry/postgres-release/releases/tag/v25) that includes your PR has been created.
