### ISSUE TITLE
Postgres doesn't restart when VM manually restarted via vcentre

### ISSUE THREAD

**Issue by neil-hickey** [cloudfoundry/postgres-release#37]
When restarting postgres on vsphere using vcentre, the startup script fails due to it missing:

`/var/vcap/sys/run/postgres` directory.

`/var/vcap/jobs/postgres/bin/postgres_ctl: line 18: /var/vcap/sys/run/postgres/postgresctl.pid: No
such file or directory`

The monit start control script could not read the `pid` file it was expecting and fails.

When this folder structure is manually created before starting the process, postgres restarts correctly.

When restarted via bosh, the process restarts successfully, however when restarting manually in vcentre it fails.

The start script should be changed to check for this file before using it.

**Comment by valeriap** [comment]
@neil-hickey 
Which version of postgres-release are you using?
This issue has been fixed in [v24](https://github.com/cloudfoundry/postgres-release/releases/tag/v24).

**Comment by neil-hickey** [comment]
hi @valeriap we were using v23, good to know its fixed! thanks
