### ISSUE TITLE
postgres creates roles and databases in the `post-start` script now.

### ISSUE THREAD

**Issue by chhhavi** [cloudfoundry/postgres-release#38]
I noticed in the latest `postgres-release`, you guys have moved the logic of creating roles and databases to the `post-start` script. Is there a reason you did this?

 In many releases (UAA and CredHub), we need those roles and databases to start. If they are being done in 'post-start', we can't start.

**Comment by valeriap** [comment]
@chhhavi 
Thanks for reporting it.
We did this change to fix an issue related to not reporting back an error in creating/updating roles and databases. The monit job is currently linked directly to the PostgreSQL status, behaviour that I would prefer not to change, and eventual failures in the control job after the PostgreSQL start were ignored. Considering that this action is not needed at each start but only after a deployment, the post-start looked as the good place. 
But I got your concern that it's related to colocating the postgres job with the client that uses it and we will take this scenario into account.

**Comment by valeriap** [comment]
@chhhavi 
We are currently working on a [feature](https://www.pivotaltracker.com/story/show/151147876) that introduces hooks that are invoked before and after postgreSQL start and stop.
The post-start hook could be used to create the databases and roles earlier.
Would the usage of this hook be sufficient for your use case?

**Comment by chhhavi** [comment]
This looks like this could work for our use case.

**Comment by vito** [comment]
@valeriap Will using the new feature require people using this release to configure something in order to support co-location? Or will this be back to working as it did before by default?

**Comment by valeriap** [comment]
@vito we went further on this issue and we introduced a new monit process dedicated to roles and db creation. See [commit](https://github.com/cloudfoundry/postgres-release/commit/68c36021c8d113b2a0adb62bf12b766be4d7b5f2).
With this new process no additional configuration is needed for co-location.
We will bump a new release with this change soon.

**Comment by valeriap** [comment]
Closing the issue since [v27](https://github.com/cloudfoundry/postgres-release/releases/tag/v27) is available. 
Please reopen if you still see issues.
