### ISSUE TITLE
How do i add config for streaming replication.

### ISSUE THREAD

**Issue by kkitai** [cloudfoundry/postgres-release#45]
Hi.

Now, I'm going to build streaming replication environment.
To realize it, It needs to add role for replication and add connection setting at pg_hba.conf.
role config is editable in this release from [here](https://github.com/cloudfoundry/postgres-release/blob/develop/jobs/postgres/spec#L53). But pg_hba.conf seems to be [not so](https://github.com/cloudfoundry/postgres-release/blob/develop/jobs/postgres/templates/pg_hba.conf.erb).

Is there something way to edit pg_hba.conf?

**Comment by valeriap** [comment]
@kkitai 
The postgres-release doesn’t directly support a streaming replica customisation.
In particular there is no property to update the pg_hba.conf.

**Comment by kkitai** [comment]
@valeriap 
okay. I found pre_start hook property and Temporarily I use it for workaround.
thank you.

```
- type: replace
  path: /instance_groups/name=db/jobs/name=postgres/properties/databases/hooks?/pre_start?
  value: |
    #!/bin/bash
    DATA_DIR="/var/vcap/store/postgres/postgres-9.6.8/"
    PG_HBA="${DATA_DIR}/pg_hba.conf"
    ls -ltra $PG_HBA
    echo "local   replication    rep                                     password" >> $PG_HBA
    echo "host    replication    rep             ((nw_cidr))             password" >> $PG_HBA
```
