### ISSUE TITLE
postgres 9.6.11 is out

### ISSUE THREAD

**Issue by thelangley** [cloudfoundry/postgres-release#47]
v9.6.11 is out with some tasty bug fixes.

Could the blobs/packages/jobs please be updated?

**Comment by valeriap** [comment]
@thelangley we recently upgraded to PostgreSQL 11.1. See [v32](https://github.com/cloudfoundry/postgres-release/releases/tag/v32). You can upgrade to it.

**Comment by thelangley** [comment]
Ahh I misunderstood the notes. For some reason I thought that both versions would be maintained for a period but if it's a bump we need to do then we can try this out 👍 

Thanks Valeria
