### ISSUE TITLE
Upgrade to Postgres 11.3 once it's out

### ISSUE THREAD

**Issue by vito** [cloudfoundry/postgres-release#50]
Hi there! We on Concourse team are affected by a [bug](https://www.postgresql.org/message-id/flat/20190207014719.GJ29720@telsasoft.com) present in Postgres 11.2 that causes Postgres to lock up until it's force-restarted. The fix is expected to be in 11.3, which should be out this week (on May 9) according to their [roadmap](https://www.postgresql.org/developer/roadmap/). 

We're at a point where we're evaluating downgrading to to Postgres 9.6, switching to CloudSQL, or just waiting on 11.3 and force-restarting our Postgres whenever it falls over. The last item involves the least amount of work, so I figured I'd open this preemptively in hopes y'all have bandwidth to publish a new release shortly after it's out. 🙂

Alternatively, we may be able to work-around the bug by disabling parallel queries, so no rush.

Thanks!

**Comment by valeriap** [comment]
@vito Thanks for raising it. We will upgrade to 11.3 once published.

**Comment by vito** [comment]
Looks like it just came out: https://www.postgresql.org/docs/11/release-11-3.html

**Comment by cirocosta** [comment]
> Fix race conditions in management of dynamic shared memory (Thomas Munro)
> These could lead to “dsa_area could not attach to segment” or “cannot unpin a segment that is not pinned” errors.

🙌

**Comment by valeriap** [comment]
@vito [postgres release v37](https://github.com/cloudfoundry/postgres-release/releases/tag/v37) has been released with the upgrade to PostgreSQL 11.3.

**Comment by vito** [comment]
@valeriap Thanks! Looks like our pipeline deployed it already. I'll close this out. :+1:
