### ISSUE TITLE
how to make this postgres as a service broker with my native Cloud Foundry?

### ISSUE THREAD

**Issue by zhangrl-mark** [cloudfoundry/postgres-release#51]
i want to push this php demo to my natvie Cloud foundry, but this demo need pgsql services.
  https://github.com/cloudfoundry-samples/cf-ex-pgbouncer

i have deploy this postgres-release on my native Cloud foundry, but how can i make it as a services and to be bindable by App(php,java,python etc)?
cf create-service-broker SERVICE_BROKER USERNAME PASSWORD URL
cf marketplace
cf create-service SERVICE PLAN SERVICE_INSTANCE [-b BROKER]
much thanks!

my env: vSphere-ESXi.6.5 + VCSA-all.6.7.0 + bosh-deployment(bosh.268.6.0) + cf-deployment(cf.v8.1.0)

**Comment by valeriap** [comment]
@zhangrl-mark In the cloudfroundry-community you can find several example service broker applications that you can refer to as starting point for developing your own service broker.
See for example the [postgresql-cf-service-broker](https://github.com/cloudfoundry-community/postgresql-cf-service-broker)

**Comment by zhangrl-mark** [comment]
much thanks,  i also found postgresql-cf-service-broker later.  i will try it this week.
thank you!
@valeriap
