### ISSUE TITLE
add the single-transaction option in restore

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/postgres-release#54]
currently when we have some intermittent issues when restoring our database.
this would be solved when we add the `single-transaction` option to
https://github.com/cloudfoundry/postgres-release/blob/develop/jobs/bbr-postgres-db/templates/restore.sh.erb#L34

would you consider accepting a PR?
1) single-transaction by default
2) single-transaction as optional

**Comment by valeriap** [comment]
@ramonskie A PR is welcome.
The good of this option is that any error would rollback the entire restore.
Anyway this is also a drawback if you are restoring a big database and the restore would last hours.
For this reason I would prefer it to be optional.

**Comment by valeriap** [comment]
@ramonskie Thanks for the PR.
I plan to create a new release containing your commit as soon as the new PostgreSQL release will be available (planned for February 13th).

**Comment by ramonskie** [comment]
you are awsome and thanks for your patience

**Comment by valeriap** [comment]
[Release v41](https://github.com/cloudfoundry/postgres-release/releases/tag/v41) created.
