### ISSUE TITLE
Is there a plan to get to Postgres Version 12 or 13? 

### ISSUE THREAD

**Issue by phebous** [cloudfoundry/postgres-release#58]
I have requirements to upgrade postgres from 11.9 to version 12.  Is there a plan to upgrade this?

**Comment by valeriap** [comment]
@phebous At the moment there's no plan to upgrade to PostgreSQL 12.
Do you have specific needs that requires this major upgrade?

**Comment by phebous** [comment]
yes...  I need v12 for the extension of Timescaledb.   Without it, I am not able to setup Prometheus remote storage going to Postgres.

**Comment by valeriap** [comment]
@phebous I confirm that a major upgrade is not planned in the short-term, but in any case I've opened a [story](https://www.pivotaltracker.com/story/show/175760454) to investigate the impact of this upgrade.

**Comment by phebous** [comment]
Valeriap,

I have updated the version to 12.4   You can find it here: https://github.com/phebous/postgres-release.   I didn't see anything that challenging with the upgrade.  I will say I didn't perform any of the regression tests since upgrades and the like didn't fit my use case.  It works fine for new installs.  

Thanks for your attention.
