### ISSUE TITLE
roles.sq.erb has a bug. 

### ISSUE THREAD

**Issue by phebous** [cloudfoundry/postgres-release#59]
Hello, 

I am trying to leverage the permissions  attribute in the manifest with the following: 

roles: 
   - name: postgres
     password: postgrespassword
     permission: SUPERUSER 

In the customizing documentation: 
    databases.roles[n].permissions | A list of attributes for the role. For the complete list of attributes, refer to ALTER ROLE command options.

Looking at the command options for postgres, I found this: 

ALTER ROLE name [ [ WITH ] option [ ... ] ]

where option can be:

      SUPERUSER | NOSUPERUSER
    | CREATEDB | NOCREATEDB
    | CREATEROLE | NOCREATEROLE
    | CREATEUSER | NOCREATEUSER
    | INHERIT | NOINHERIT
    | LOGIN | NOLOGIN
    | REPLICATION | NOREPLICATION
    | CONNECTION LIMIT connlimit
    | [ ENCRYPTED | UNENCRYPTED ] PASSWORD 'password'
    | VALID UNTIL 'timestamp'

so my above manifest should be correct.  However, roles.permission attribute calls roles.sql.erb: 

<% p("databases.roles", []).each do |role| %>
DO
$body$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = '<%= role["name"] %>') THEN
      CREATE ROLE "<%= role["name"] %>" WITH LOGIN;
   END IF;
END
$body$;
  <% if role["password"] %>
ALTER ROLE "<%= role["name"] %>" WITH LOGIN PASSWORD '<%= role["password"] %>';
  <% end %>
  <% if role["permissions"] %>
ALTER ROLE "<%= role["name"] %>" WITH <%= role["permissions"].join(' ') %>;
  <% end %>

This successfully creates the user name and sets the password.  However, when the role["permissions"] exists, this will call the alter role role["name"] with role["permissions"].join(' ').     What is the purpose of the .join(' ') at the end?   It will error out with this error: 

   - Error filling in template 'roles.sql.erb' (line 14: undefined method `join' for "SUPERUSER":String)

shouldn't .join be removed?

**Comment by valeriap** [comment]
Hi @phebous,
you can set multiple permissions to a role; for this reason the property is an array.
So in your case, the manifest should be:
```
roles:
  name: postgres
  password: postgrespassword
  permissions:
  - SUPERUSER
```
Please, note that the property has an `s` at the end.
I hope this helps.

**Comment by phebous** [comment]
That makes sense.  I knew I was missing something... 

Thanks!
