### ISSUE TITLE
upgrade to postgres 13.

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/postgres-release#61]
as bosh is now also using postgres 13.
is it not a good idea we bump this to postgres 13 as well.

the question for bumping has been suggested 2 years ago #58
but action has been taken since than.

so are there any updates on this?

**Comment by benjaminguttmann-avtq** [comment]
Are there any actions planned on adding psql13 ?

**Comment by ZPascal** [comment]
Hi Ramon and @benjaminguttmann-avtq, I think we can close the issue and PR. The new v46 release adds PSQL [13](https://github.com/cloudfoundry/postgres-release/blob/fb4198c262d5853926e861b9d0e6dc8ac40a28bc/releases/postgres/postgres-46.yml#L13) and [15](https://github.com/cloudfoundry/postgres-release/blob/fb4198c262d5853926e861b9d0e6dc8ac40a28bc/releases/postgres/postgres-46.yml#L14) support.

**Comment by ramonskie** [comment]
please not that there is currently a bug see https://github.com/cloudfoundry/postgres-release/issues/73
