### ISSUE TITLE
Upgrade to Postgres 12

### ISSUE THREAD

**Issue by myeghiazarya** [cloudfoundry/postgres-release#65]
There were some vulnerability issues in the older version of Postgres, so upgrading to 12v will resolve some problems in our project.

**Comment by benjaminguttmann-avtq** [comment]
Are there any actions planned on adding psql12 ?

**Comment by jbooherl** [comment]
We are hoping to be able to support TLS 1.2 for connections which requires Postgres 12

**Comment by benjaminguttmann-avtq** [comment]
I think the current plan for the next release is mentioned in here #68

**Comment by jbooherl** [comment]
Awesome, I'll link that story in our tracker!

**Comment by ZPascal** [comment]
The current release `v46` supports now PostgreSQL 11, 13 and 15. @myeghiazarya Is PostgreSQL v12 still a requirement from your side or can we close the issue?

**Comment by jpalermo** [comment]
Thanks for the update!
