### ISSUE TITLE
[Feature] Add the possiblity to specify the used PostgreSQL version

### ISSUE THREAD

**Issue by ZPascal** [cloudfoundry/postgres-release#74]
**Current state:**
It's currently only possible to consume the default major version (currently PG 15) via the PostgreSQL Bosh release. 

**Improvement idea:**
It should be possible to configure the used major version.

**Comment by jpalermo** [comment]
@Jobsby is currently working on a solution for this

**Comment by ZPascal** [comment]
The problem was solved by PR #75. I am closing the case.
